name: Call_My_first_code

on:
  workflow_dispatch 
    #branches:
     # - main  # Adjust this to the branch you want to trigger this workflow

jobs:
  trigger-workflow:
    uses: ./.github/workflows/My_first_code.yaml
      
