name: Call_reusable_wf_n_use_its_op

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/reusable_output.yaml
    

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

